version: '3'
services:
  projeto_ead_admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto_ead_backend
    ports:
      - "3003:3000"
    volumes:
      - .:/app
    restart: always
